### ISSUE TITLE
Header is missing

### ISSUE THREAD

**Issue by gplssm** [gplssm/ding0_viz#5]
Add with basic info is needed to welcome the user.

### Tasks

- [x] Add title
- [x] Welcome paragraph
- [x] Explain what's shown
- [x] Explain how to use
- [x] Add logo
- [ ] Maybe add navbar

**Comment by gplssm** [comment]
Nav will be done later
